# RG
CORE_RESOURCE_GROUP_NAME = "rg-{}"
WORKSPACE_RESOURCE_GROUP_NAME = "rg-{}-ws-{}"

IMPORT_TYPE = "import"
EXPORT_TYPE = "export"
# Import
STORAGE_ACCOUNT_NAME_IMPORT_EXTERNAL = "stalimex{}"
STORAGE_ACCOUNT_NAME_IMPORT_INPROGRESS = "stalimip{}"
STORAGE_ACCOUNT_NAME_IMPORT_APPROVED = "stalimappws{}"
STORAGE_ACCOUNT_NAME_IMPORT_REJECTED = "stalimrej{}"
STORAGE_ACCOUNT_NAME_IMPORT_BLOCKED = "stalimblocked{}"

# Export
STORAGE_ACCOUNT_NAME_EXPORT_INTERNAL = "stalexintws{}"
STORAGE_ACCOUNT_NAME_EXPORT_INPROGRESS = "stalexipws{}"
STORAGE_ACCOUNT_NAME_EXPORT_APPROVED = "stalexapp{}"
STORAGE_ACCOUNT_NAME_EXPORT_REJECTED = "stalexrejws{}"
STORAGE_ACCOUNT_NAME_EXPORT_BLOCKED = "stalexblockedws{}"

# Workspace MHRA costs
STORAGE_ACCOUNT_NAME_CORE_RESOURCE_GROUP = "stg{}"
STORAGE_ACCOUNT_NAME_WORKSPACE_RESOURCE_GROUP_SSBS = "ssbsws{}"
STORAGE_ACCOUNT_NAME_WORKSPACE_RESOURCE_GROUP_GENERAL = "stgws{}"
WORKSPACE_COSTS_TABLE_NAME = "workspacecosts"
WORKSPACE_AZURE_COSTS_TABLE_NAME = "workspaceazurecosts"

# Workspace MHRA costs
WORKSPACE_CONTAINER_USAGE_TABLE_NAME = "storageusage"
WORKSPACE_FILESHARE_USAGE_TABLE_NAME = "fileshareusage"
WORKSPACE_PERSTUDY_USAGE_TABLE_NAME  = "perstudyusage"

CORE_KEYVAULT_NAME = "kv-{}"
WS_KEYVAULT_NAME = "kv-{}-ws-{}"
CORE_VNET_NAME = "vnet-{}"

# Used for creating SSBS containers
PROTOCOL_CONTAINER_ASSINED_USERS_ENTRA_GROUP = "{}-ws-{}-{}"
SSBS_STORAGE_ACCOUNT_ACCESS_ROLE_NAME = "Storage Blob Data Contributor"
EXPLORE_WORKSPACE_SSBS_ORIGIN_FOLDER = "SendToAnalysee"
