variable "tre_id" {}
variable "location" {}
variable "resource_group_name" {}
variable "shared_subnet_id" {}
variable "web_app_subnet_id" {}
variable "blob_core_dns_zone_id" {}
variable "tre_core_tags" {}
variable "core_storage_name" {}
variable "cosmosdb_account_id" {}
